# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2148db9e4218fd53e236d953511882e510806a282c4313c197752e4e090183ef24bbff9e5c781f250f8675eb015fe0a2a24e90ebada12313fad550eb1bce42fa

test:
  secret_key_base: 1db0d9daa1c8f5f5261dd3f70c5d08927c3a1f6ce767ca8fb925cdebc11a6189a8a048f339756eed0787685e040f9bac9aa086b59b10f986eb5902d167c48e4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
